/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Usuario } from './usuario';

export interface Admision { 
    canton?: string;
    codUd?: string;
    direccP?: string;
    emergencia?: string;
    empresa?: string;
    estadoC?: string;
    fecha?: Date;
    fechaA?: Date;
    fuente?: string;
    idAdmision?: number;
    instruccion?: string;
    instutucionSistema?: string;
    nombre?: string;
    numero?: string;
    ocupacion?: string;
    parantesco?: string;
    parroquia?: string;
    persona?: string;
    provincia?: string;
    referidoD?: string;
    servicio?: string;
    telefono?: string;
    tipoS?: string;
    unidadOperativa?: string;
    usuario?: Usuario;
}