/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Usuario } from './usuario';

export interface Anestesia { 
    anestecio?: string;
    ayudanteA?: string;
    ayudanteC?: string;
    cama?: number;
    cirujano?: string;
    estatura?: number;
    fecha?: Date;
    horaA?: number;
    horaO?: number;
    idAnes?: number;
    intrumentista?: string;
    minA?: number;
    minO?: number;
    ocupacion?: string;
    peso?: number;
    post?: string;
    pre?: string;
    propuesta?: string;
    realizada?: string;
    sala?: string;
    servicio?: string;
    tecnica?: string;
    tipoD?: string;
    usuario?: Usuario;
}