/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Usuario } from './usuario';

export interface Autorizacion { 
    cama?: string;
    canton?: string;
    cedulaMe?: string;
    cedulaRe?: string;
    cedulaTra?: string;
    codUd?: string;
    fecha?: Date;
    idAutorizacion?: number;
    instutucionSistema?: string;
    nombre?: string;
    nombreMedico?: string;
    nombreRepre?: string;
    nombreTratante?: string;
    numeroHistoriaClinica?: number;
    parentesco?: string;
    parroquia?: string;
    provincia?: string;
    sala?: string;
    servicio?: string;
    telefonoMedico?: string;
    telefonoParien?: string;
    telefonoTra?: string;
    unidadOperativa?: string;
    usuario?: Usuario;
}