/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ConsultaExternaByIdDTO { 
    abdomen?: string;
    c?: string;
    cabeza?: string;
    cancer?: boolean;
    cardiopatia?: boolean;
    cardiovascular?: string;
    cie?: string;
    clinicos?: string;
    cuello?: string;
    descripcion?: string;
    descripcionDiagnostico?: string;
    descripcionPreDef?: string;
    descripcionPreDefCie?: string;
    descripcionPreDefPreDef?: string;
    diabetes?: boolean;
    digestivo?: string;
    duracionConsulta?: string;
    endocrino?: string;
    enfCardiovasculares?: boolean;
    enfInfecciosas?: boolean;
    enfMentales?: boolean;
    enfermedadActual?: string;
    establecimiento?: string;
    extremidades?: string;
    familiares?: string;
    fecha?: Date;
    fechaMedicion?: Date;
    frecRespiratoria?: number;
    genital?: string;
    hemolenfatico?: string;
    hipertension?: boolean;
    historiaClinica?: number;
    i?: string;
    idConsexterna?: number;
    identificacion?: string;
    l?: string;
    m?: string;
    malformaciones?: boolean;
    motivoConsulta?: string;
    musculoEsqueletico?: string;
    nervioso?: string;
    nombres?: string;
    nombresProfesional?: string;
    o?: string;
    observaciones?: string;
    organoSentido?: string;
    otros?: boolean;
    pelvis?: string;
    peso?: number;
    preDef?: string;
    presionArterial?: string;
    pulso?: number;
    quirurgicos?: string;
    r?: string;
    respiratorio?: string;
    sexo?: string;
    t?: string;
    talla?: number;
    temperatura?: number;
    torax?: string;
    tuberculosis?: boolean;
    urinario?: string;
}