/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ConsentimientoTratamientoDto { 
    cama?: string;
    canton?: string;
    codUd?: string;
    codigo?: number;
    especialidad?: string;
    estado?: string;
    fecha?: Date;
    idConsentimiento?: number;
    idConsentimientoFK?: number;
    idInfTrat?: number;
    institucionSistema?: string;
    nombreProfesional?: string;
    numeroHistoriaClinica?: number;
    parroquia?: string;
    procedimientoPropuesto?: string;
    proposito?: string;
    provincia?: string;
    resultadoEsperado?: string;
    riesgoComplicaciones?: string;
    sala?: string;
    servicio?: string;
    telefono?: number;
    unidadOperativa?: string;
}