/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Formulario } from './formulario';

export interface Contrareferencia { 
    distrito?: string;
    entidad?: string;
    especialS?: string;
    establecimiento?: string;
    fecha?: string;
    formulario?: Formulario;
    idContra?: number;
    justificada?: string;
    numCli?: string;
    servicio?: string;
    tipo?: string;
}