/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Formulario } from './formulario';

export interface DatosInstitucionalesReq { 
    ausencia?: string;
    codigo?: string;
    descripcion?: string;
    districto?: string;
    entidad?: string;
    establecimiento?: string;
    falta?: string;
    formulario?: Formulario;
    histClinNum?: string;
    histclinnum?: string;
    idDatos?: number;
    limitada?: string;
    nombreP?: string;
    otros?: string;
    satu?: string;
    tipo?: string;
}