/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Admision } from './admision';

export interface Emergencia { 
    abortos?: string;
    admision?: Admision;
    borramiento?: string;
    cesareas?: string;
    contraciones?: string;
    dilatacion?: string;
    fecha?: Date;
    fetal?: string;
    frecuencia?: string;
    gestas?: string;
    idEmergencia?: number;
    membranas?: string;
    partos?: string;
    plano?: string;
    presentacion?: string;
    semanas?: string;
    snagrado?: string;
    tiempo?: number;
    uterina?: string;
    util?: string;
}