/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Usuario } from './usuario';

export interface Formulario { 
    cie1?: string;
    cie2?: string;
    contra?: string;
    cuadroClinico?: string;
    dato?: string;
    dato2?: string;
    derivacion?: string;
    diagnostico?: string;
    diagnostico2?: string;
    hallazgos?: string;
    idFormulario?: number;
    inversa?: string;
    referencia?: string;
    usuario?: Usuario;
}