/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DatosInstitucionales } from './datosInstitucionales';
import { RefiereDeriva } from './refiereDeriva';
import { Usuario } from './usuario';

export interface Formulario { 
    cuadroClinico?: string;
    datos?: DatosInstitucionales;
    diagnostico?: string;
    hallazgos?: string;
    idFormulario?: number;
    refiere?: RefiereDeriva;
    usuario?: Usuario;
}