/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Farmacia } from './farmacia';

export interface GenericResponseListFarmacia { 
    message?: string;
    object?: Array<Farmacia>;
    status?: number;
}