/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Admision } from './admision';

export interface IngresoDia { 
    admision?: Admision;
    cie1?: string;
    cie2?: string;
    cie3?: string;
    d1?: string;
    d2?: string;
    d3?: string;
    descripcion1?: string;
    descripcion2?: string;
    descripcion3?: string;
    idDiagI?: number;
}