/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Admision } from './admision';

export interface Lesiones { 
    admision?: Admision;
    cerrada?: string;
    cortante?: string;
    esguince?: string;
    excoracion?: string;
    expuesta?: string;
    extraa?: string;
    hematoma?: string;
    hemorragia?: string;
    idLesiones?: number;
    inflamacion?: string;
    masa?: string;
    mordedura?: string;
    pentrante?: string;
    picadura?: string;
    quemadura?: string;
}