/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MedicoConsentimiento { 
    alergia?: string;
    cedula?: string;
    codigo?: string;
    direccion?: string;
    edad?: number;
    entidad?: string;
    especialidad?: string;
    estado?: number;
    fecha?: Date;
    fechaNaci?: Date;
    idMediC?: number;
    nombreDoc?: string;
    nombrePaciente?: string;
    personaA?: string;
    procedimientos?: string;
    telefono?: string;
}