/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Usuario } from './usuario';

export interface Medicamentos { 
    abreviaturaFun?: string;
    establecimiento?: string;
    fecha?: Date;
    hora?: string;
    idMedicamentos?: number;
    inicialesRespon?: string;
    nombreMedicamento?: string;
    usuario?: Usuario;
}