/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Usuario } from './usuario';

export interface Odontologia { 
    codigo?: string;
    diagnostico?: string;
    enfermedad?: string;
    establecimiento?: string;
    fecha?: Date;
    frecCardiaca?: number;
    frecRespi?: number;
    idOdonto?: number;
    motivo?: string;
    prescripcion?: string;
    presion?: number;
    procedimiento?: string;
    sesion?: string;
    temperatura?: number;
    usuario?: Usuario;
}