/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConsultaExterna } from './consultaExterna';

export interface RevOrganoSistem { 
    cardiovascular?: string;
    consultaExterna?: ConsultaExterna;
    descripcion?: string;
    digestivo?: string;
    endocrino?: string;
    genital?: string;
    hemoLenfatico?: string;
    idRevOrganoSistem?: number;
    musculoEsqueletico?: string;
    nervioso?: string;
    organoSentido?: string;
    respiratorio?: string;
    urinario?: string;
}