/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Rol { 
    id?: number;
    rolNombre?: Rol.RolNombreEnum;
}
export namespace Rol {
    export type RolNombreEnum = 'ROLE_ADMINISTRADOR' | 'ROLE_COORDINADOR' | 'ROLE_ESTUDIANTE' | 'ROLE_TRIBUNAL' | 'ROLE_TUTOR';
    export const RolNombreEnum = {
        ADMINISTRADOR: 'ROLE_ADMINISTRADOR' as RolNombreEnum,
        COORDINADOR: 'ROLE_COORDINADOR' as RolNombreEnum,
        ESTUDIANTE: 'ROLE_ESTUDIANTE' as RolNombreEnum,
        TRIBUNAL: 'ROLE_TRIBUNAL' as RolNombreEnum,
        TUTOR: 'ROLE_TUTOR' as RolNombreEnum
    };
}