/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Odontologia } from './odontologia';

export interface SaludBucal { 
    angleI?: string;
    angleII?: string;
    angleIII?: string;
    cal1?: number;
    cal2?: number;
    cal3?: number;
    cal4?: number;
    cal5?: number;
    calcul6?: number;
    gin1?: number;
    gin2?: number;
    gin3?: number;
    gin4?: number;
    gin5?: number;
    gin6?: number;
    idSalud?: number;
    leve?: string;
    leveF?: string;
    moderada?: string;
    moderadaF?: string;
    odontologia?: Odontologia;
    p11?: string;
    p16?: string;
    p17?: string;
    p21?: string;
    p26?: string;
    p27?: string;
    p31?: string;
    p36?: string;
    p37?: string;
    p41?: string;
    p46?: string;
    p47?: string;
    p55?: string;
    p65?: string;
    p71?: string;
    p75?: string;
    p85?: string;
    placa1?: number;
    placa2?: number;
    placa3?: number;
    placa4?: number;
    placa5?: number;
    placa6?: number;
    severa?: string;
    severaF?: string;
    toatlG1?: number;
    toatlP1?: number;
    totalC2?: number;
}