/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Admision } from './admision';

export interface SignosE { 
    abdomen?: string;
    admision?: Admision;
    axilar?: number;
    bucal?: number;
    cabeza?: string;
    capilar?: number;
    columna?: string;
    cuello?: string;
    descripcion?: string;
    extremidades?: string;
    fCardiaca?: number;
    idSgnos?: number;
    motora?: number;
    ocular?: number;
    oxigeno?: number;
    pelvis?: string;
    peso?: number;
    presion?: number;
    pupilaD?: string;
    pupilaI?: string;
    respira?: number;
    talla?: number;
    torax?: string;
    total?: number;
    verbal?: number;
    viaObost?: string;
}