/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Cliente } from './cliente';
import { Empleado } from './empleado';

export interface Tratamiento {
    cantidad?: number;
    categoria?: string;
    cliente?: Cliente;
    codigo?: string;
    descripcion?: string;
    empleado?: Empleado;
    estado?: number;
    idTratamiento?: number;
    nombre?: string;
    subtotal?: number;
    total?: number;
    valor_unitario?: number;
}
