/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Tratamiento { 
    cantidad?: number;
    categoria?: string;
    codigo?: string;
    descripcion?: string;
    estado?: number;
    idTratamiento?: number;
    nombre?: string;
    subtotal?: number;
    total?: number;
    valorUnitario?: number;
}