/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Admision } from './admision';

export interface TrataM { 
    admision?: Admision;
    idTrat?: number;
    indicaciones?: string;
    medica1?: string;
    medica2?: string;
    medica3?: string;
    poso3?: string;
    posologia1?: string;
    posologia2?: string;
}