export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './clienteController.service';
import { ClienteControllerService } from './clienteController.service';
export * from './cuerpoFacturaController.service';
import { CuerpoFacturaControllerService } from './cuerpoFacturaController.service';
export * from './empleadoController.service';
import { EmpleadoControllerService } from './empleadoController.service';
export * from './facturaController.service';
import { FacturaControllerService } from './facturaController.service';
export * from './productoController.service';
import { ProductoControllerService } from './productoController.service';
export * from './proveedorController.service';
import { ProveedorControllerService } from './proveedorController.service';
export * from './sucursalController.service';
import { SucursalControllerService } from './sucursalController.service';
export const APIS = [AuthControllerService, BasicErrorControllerService, ClienteControllerService, CuerpoFacturaControllerService, EmpleadoControllerService, FacturaControllerService, ProductoControllerService, ProveedorControllerService, SucursalControllerService];
