export * from './antecFamiliaresController.service';
import { AntecFamiliaresControllerService } from './antecFamiliaresController.service';
export * from './antecPersonalesController.service';
import { AntecPersonalesControllerService } from './antecPersonalesController.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './clienteController.service';
import { ClienteControllerService } from './clienteController.service';
export * from './consentimientoController.service';
import { ConsentimientoControllerService } from './consentimientoController.service';
export * from './consultaExternaController.service';
import { ConsultaExternaControllerService } from './consultaExternaController.service';
export * from './cuerpoFacturaController.service';
import { CuerpoFacturaControllerService } from './cuerpoFacturaController.service';
export * from './diagnosticoController.service';
import { DiagnosticoControllerService } from './diagnosticoController.service';
export * from './empleadoController.service';
import { EmpleadoControllerService } from './empleadoController.service';
export * from './examFisicoRegionalController.service';
import { ExamFisicoRegionalControllerService } from './examFisicoRegionalController.service';
export * from './facturaController.service';
import { FacturaControllerService } from './facturaController.service';
export * from './familiaresController.service';
import { FamiliaresControllerService } from './familiaresController.service';
export * from './faramaciaController.service';
import { FaramaciaControllerService } from './faramaciaController.service';
export * from './informacionTratamientoController.service';
import { InformacionTratamientoControllerService } from './informacionTratamientoController.service';
export * from './medicamentosController.service';
import { MedicamentosControllerService } from './medicamentosController.service';
export * from './planTratamientoController.service';
import { PlanTratamientoControllerService } from './planTratamientoController.service';
export * from './productoController.service';
import { ProductoControllerService } from './productoController.service';
export * from './proveedorController.service';
import { ProveedorControllerService } from './proveedorController.service';
export * from './residenciaController.service';
import { ResidenciaControllerService } from './residenciaController.service';
export * from './revOrganoSistemController.service';
import { RevOrganoSistemControllerService } from './revOrganoSistemController.service';
export * from './sigVitAntropometriaController.service';
import { SigVitAntropometriaControllerService } from './sigVitAntropometriaController.service';
export * from './sucursalController.service';
import { SucursalControllerService } from './sucursalController.service';
export * from './tarjetaController.service';
import { TarjetaControllerService } from './tarjetaController.service';
export * from './tarjetaEspecialidadController.service';
import { TarjetaEspecialidadControllerService } from './tarjetaEspecialidadController.service';
export * from './tratamientoController.service';
import { TratamientoControllerService } from './tratamientoController.service';
export const APIS = [AntecFamiliaresControllerService, AntecPersonalesControllerService, AuthControllerService, BasicErrorControllerService, ClienteControllerService, ConsentimientoControllerService, ConsultaExternaControllerService, CuerpoFacturaControllerService, DiagnosticoControllerService, EmpleadoControllerService, ExamFisicoRegionalControllerService, FacturaControllerService, FamiliaresControllerService, FaramaciaControllerService, InformacionTratamientoControllerService, MedicamentosControllerService, PlanTratamientoControllerService, ProductoControllerService, ProveedorControllerService, ResidenciaControllerService, RevOrganoSistemControllerService, SigVitAntropometriaControllerService, SucursalControllerService, TarjetaControllerService, TarjetaEspecialidadControllerService, TratamientoControllerService];
