export * from './antecFamiliaresController.service';
import { AntecFamiliaresControllerService } from './antecFamiliaresController.service';
export * from './antecPersonalesController.service';
import { AntecPersonalesControllerService } from './antecPersonalesController.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './autorizacionController.service';
import { AutorizacionControllerService } from './autorizacionController.service';
export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './clienteController.service';
import { ClienteControllerService } from './clienteController.service';
export * from './consentimientoController.service';
import { ConsentimientoControllerService } from './consentimientoController.service';
export * from './consultaExternaController.service';
import { ConsultaExternaControllerService } from './consultaExternaController.service';
export * from './cuerpoFacturaController.service';
import { CuerpoFacturaControllerService } from './cuerpoFacturaController.service';
export * from './diagnosticoController.service';
import { DiagnosticoControllerService } from './diagnosticoController.service';
export * from './empleadoController.service';
import { EmpleadoControllerService } from './empleadoController.service';
export * from './equiposController.service';
import { EquiposControllerService } from './equiposController.service';
export * from './evolucionController.service';
import { EvolucionControllerService } from './evolucionController.service';
export * from './examFisicoRegionalController.service';
import { ExamFisicoRegionalControllerService } from './examFisicoRegionalController.service';
export * from './facturaController.service';
import { FacturaControllerService } from './facturaController.service';
export * from './familiaresController.service';
import { FamiliaresControllerService } from './familiaresController.service';
export * from './faramaciaController.service';
import { FaramaciaControllerService } from './faramaciaController.service';
export * from './formularioController.service';
import { FormularioControllerService } from './formularioController.service';
export * from './historiaController.service';
import { HistoriaControllerService } from './historiaController.service';
export * from './informacionTratamientoController.service';
import { InformacionTratamientoControllerService } from './informacionTratamientoController.service';
export * from './medicamentosController.service';
import { MedicamentosControllerService } from './medicamentosController.service';
export * from './medicoConsentimientoController.service';
import { MedicoConsentimientoControllerService } from './medicoConsentimientoController.service';
export * from './organosController.service';
import { OrganosControllerService } from './organosController.service';
export * from './planTratamientoController.service';
import { PlanTratamientoControllerService } from './planTratamientoController.service';
export * from './productoController.service';
import { ProductoControllerService } from './productoController.service';
export * from './protocoloController.service';
import { ProtocoloControllerService } from './protocoloController.service';
export * from './proveedorController.service';
import { ProveedorControllerService } from './proveedorController.service';
export * from './residenciaController.service';
import { ResidenciaControllerService } from './residenciaController.service';
export * from './revOrganoSistemController.service';
import { RevOrganoSistemControllerService } from './revOrganoSistemController.service';
export * from './sigVitAntropometriaController.service';
import { SigVitAntropometriaControllerService } from './sigVitAntropometriaController.service';
export * from './sucursalController.service';
import { SucursalControllerService } from './sucursalController.service';
export * from './tarjetaController.service';
import { TarjetaControllerService } from './tarjetaController.service';
export * from './tarjetaEspecialidadController.service';
import { TarjetaEspecialidadControllerService } from './tarjetaEspecialidadController.service';
export * from './tipoQuiController.service';
import { TipoQuiControllerService } from './tipoQuiController.service';
export * from './tratamientoController.service';
import { TratamientoControllerService } from './tratamientoController.service';
export const APIS = [AntecFamiliaresControllerService, AntecPersonalesControllerService, AuthControllerService, AutorizacionControllerService, BasicErrorControllerService, ClienteControllerService, ConsentimientoControllerService, ConsultaExternaControllerService, CuerpoFacturaControllerService, DiagnosticoControllerService, EmpleadoControllerService, EquiposControllerService, EvolucionControllerService, ExamFisicoRegionalControllerService, FacturaControllerService, FamiliaresControllerService, FaramaciaControllerService, FormularioControllerService, HistoriaControllerService, InformacionTratamientoControllerService, MedicamentosControllerService, MedicoConsentimientoControllerService, OrganosControllerService, PlanTratamientoControllerService, ProductoControllerService, ProtocoloControllerService, ProveedorControllerService, ResidenciaControllerService, RevOrganoSistemControllerService, SigVitAntropometriaControllerService, SucursalControllerService, TarjetaControllerService, TarjetaEspecialidadControllerService, TipoQuiControllerService, TratamientoControllerService];
