/**
 * Proyecto TDS Backend
 * Descripción
 *
 * OpenAPI spec version: 2.0
 * Contact: info@tecazuay.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { GenericResponseListFarmacia } from '../model/genericResponseListFarmacia';
import { GenericResponsestring } from '../model/genericResponsestring';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class FaramaciaControllerService {

    protected basePath = '//localhost:8080/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getAllFarmacias
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllFarmaciasUsingGET(observe?: 'body', reportProgress?: boolean): Observable<GenericResponseListFarmacia>;
    public getAllFarmaciasUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GenericResponseListFarmacia>>;
    public getAllFarmaciasUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GenericResponseListFarmacia>>;
    public getAllFarmaciasUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GenericResponseListFarmacia>('get',`${this.basePath}/farmacia/getAllFarmacias`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * saveFarmacia
     * 
     * @param idEmpleado 
     * @param idFarmacia 
     * @param idProducto 
     * @param sucursalCorreoSuc 
     * @param sucursalDireccionSuc 
     * @param sucursalFarmaciaIdEmpleado 
     * @param sucursalFarmaciaIdFarmacia 
     * @param sucursalFarmaciaIdProducto 
     * @param sucursalIdSucursal 
     * @param sucursalNombreSuc 
     * @param sucursalTelefonoSuc 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveFarmaciaUsingPOST(idEmpleado?: number, idFarmacia?: number, idProducto?: number, sucursalCorreoSuc?: string, sucursalDireccionSuc?: string, sucursalFarmaciaIdEmpleado?: number, sucursalFarmaciaIdFarmacia?: number, sucursalFarmaciaIdProducto?: number, sucursalIdSucursal?: number, sucursalNombreSuc?: string, sucursalTelefonoSuc?: number, observe?: 'body', reportProgress?: boolean): Observable<GenericResponsestring>;
    public saveFarmaciaUsingPOST(idEmpleado?: number, idFarmacia?: number, idProducto?: number, sucursalCorreoSuc?: string, sucursalDireccionSuc?: string, sucursalFarmaciaIdEmpleado?: number, sucursalFarmaciaIdFarmacia?: number, sucursalFarmaciaIdProducto?: number, sucursalIdSucursal?: number, sucursalNombreSuc?: string, sucursalTelefonoSuc?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GenericResponsestring>>;
    public saveFarmaciaUsingPOST(idEmpleado?: number, idFarmacia?: number, idProducto?: number, sucursalCorreoSuc?: string, sucursalDireccionSuc?: string, sucursalFarmaciaIdEmpleado?: number, sucursalFarmaciaIdFarmacia?: number, sucursalFarmaciaIdProducto?: number, sucursalIdSucursal?: number, sucursalNombreSuc?: string, sucursalTelefonoSuc?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GenericResponsestring>>;
    public saveFarmaciaUsingPOST(idEmpleado?: number, idFarmacia?: number, idProducto?: number, sucursalCorreoSuc?: string, sucursalDireccionSuc?: string, sucursalFarmaciaIdEmpleado?: number, sucursalFarmaciaIdFarmacia?: number, sucursalFarmaciaIdProducto?: number, sucursalIdSucursal?: number, sucursalNombreSuc?: string, sucursalTelefonoSuc?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {












        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idEmpleado !== undefined && idEmpleado !== null) {
            queryParameters = queryParameters.set('idEmpleado', <any>idEmpleado);
        }
        if (idFarmacia !== undefined && idFarmacia !== null) {
            queryParameters = queryParameters.set('idFarmacia', <any>idFarmacia);
        }
        if (idProducto !== undefined && idProducto !== null) {
            queryParameters = queryParameters.set('idProducto', <any>idProducto);
        }
        if (sucursalCorreoSuc !== undefined && sucursalCorreoSuc !== null) {
            queryParameters = queryParameters.set('sucursal.correoSuc', <any>sucursalCorreoSuc);
        }
        if (sucursalDireccionSuc !== undefined && sucursalDireccionSuc !== null) {
            queryParameters = queryParameters.set('sucursal.direccionSuc', <any>sucursalDireccionSuc);
        }
        if (sucursalFarmaciaIdEmpleado !== undefined && sucursalFarmaciaIdEmpleado !== null) {
            queryParameters = queryParameters.set('sucursal.farmacia.idEmpleado', <any>sucursalFarmaciaIdEmpleado);
        }
        if (sucursalFarmaciaIdFarmacia !== undefined && sucursalFarmaciaIdFarmacia !== null) {
            queryParameters = queryParameters.set('sucursal.farmacia.idFarmacia', <any>sucursalFarmaciaIdFarmacia);
        }
        if (sucursalFarmaciaIdProducto !== undefined && sucursalFarmaciaIdProducto !== null) {
            queryParameters = queryParameters.set('sucursal.farmacia.idProducto', <any>sucursalFarmaciaIdProducto);
        }
        if (sucursalIdSucursal !== undefined && sucursalIdSucursal !== null) {
            queryParameters = queryParameters.set('sucursal.idSucursal', <any>sucursalIdSucursal);
        }
        if (sucursalNombreSuc !== undefined && sucursalNombreSuc !== null) {
            queryParameters = queryParameters.set('sucursal.nombreSuc', <any>sucursalNombreSuc);
        }
        if (sucursalTelefonoSuc !== undefined && sucursalTelefonoSuc !== null) {
            queryParameters = queryParameters.set('sucursal.telefonoSuc', <any>sucursalTelefonoSuc);
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GenericResponsestring>('post',`${this.basePath}/farmacia/saveFarmacia`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
